// styles.ts
import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    gradientBackground: {
        flex: 1,
    },
    safeArea: {
        flex: 1,
    },
    keyboardView: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
        justifyContent: 'center',
        paddingHorizontal: 24,
        paddingBottom: 40,
    },

    // Estilos da Logo
    logoContainer: {
        alignItems: 'center',
        marginBottom: 10,
        marginTop: 20,

    },
    logoPlaceholder: {
        alignItems: 'center',
        justifyContent: 'center',
        opacity: 0.9,
    },
    logoText: {
        color: 'white',
        fontSize: 24,
        marginTop: 10,
        fontWeight: 'bold',
        opacity: 0.8,
    },
    logoImage: {
        width: 400,
        height: 400,
        alignSelf: 'center',
        marginBottom: 8,
    },

    // Estilos do Input
    inputContainer: {
        backgroundColor: 'white',
        borderTopLeftRadius: 4,
        borderTopRightRadius: 4,
        flexDirection: 'row',
        height: 56,
        alignItems: 'center',
        position: 'relative',
        overflow: 'hidden',
    },
    iconArea: {
        width: 48,
        height: 56,
        justifyContent: 'center',
        alignItems: 'center',
    },
    textArea: {
        flex: 1,
        justifyContent: 'center',
        height: 56,
        paddingRight: 16,
    },
    rightIcon: {
        width: 48,
        height: 56,
        justifyContent: 'center',
        alignItems: 'center',
    },
    inputLabel: {
        fontSize: 12,
        color: '#49454f',
        letterSpacing: 0.4,
    },
    inputField: {
        fontSize: 16,
        color: '#1d1b20',
        padding: 0,
        marginTop: 2,
        fontWeight: '500',
    },
    activeIndicator: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 1,
        backgroundColor: '#49454F',
    },

    // Layout do Formulário
    formArea: {
        width: '100%',
    },
    spacer: {
        height: 16,
    },

    // Link Esqueceu a Senha
    forgotPasswordButton: {
        alignSelf: 'center',
        marginTop: 16,
        marginBottom: 32,
    },
    forgotPasswordText: {
        color: 'white',
        fontSize: 14,
        fontWeight: '600',
        letterSpacing: 0.1,
        textDecorationLine: 'underline',
    },

    // Botão Entrar
    loginButton: {
        backgroundColor: '#002259',
        height: 48,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        ...(Platform.OS === 'web'
            ? { boxShadow: '0px 2px 3.84px rgba(0,0,0,0.25)' }
            : {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.25,
                shadowRadius: 3.84,
                elevation: 5,
            }),
    },
    loginButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '500',
        letterSpacing: 0.15,
    },

    // Rodapé (Admin)
    adminButton: {
        marginTop: 40,
        alignItems: 'center',
    },
    adminText: {
        color: 'white',
        fontSize: 14,
        fontWeight: '600',
    },

    // --- My Studies Screen Styles ---
    myStudiesContainer: {
        backgroundColor: '#F5F5F5', // Light gray background
    },
    headerGradient: {
        paddingTop: 0,
        paddingBottom: 20,
        // Removed border radius
    },
    headerContent: {
        paddingHorizontal: 24,
        alignItems: 'center',
    },
    headerLogo: {
        width: 140,
        height: 140,
        marginBottom: 10,
    },
    headerTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: 'white',
        marginTop: 0, // Adjusted since logo has margin
    },

    headerSubtitle: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.8)',
        marginTop: 5,
        textAlign: 'center',
    },
    searchContainer: {
        flexDirection: 'row',
        marginTop: 20,
        width: '100%',
        alignItems: 'center',
    },
    searchBar: {
        flex: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 12,
        height: 50,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        marginRight: 10,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.3)',
    },
    searchInput: {
        flex: 1,
        color: 'white',
        fontSize: 16,
        marginLeft: 10,
    },
    filterButton: {
        width: 50,
        height: 50,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.3)',
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'white',
        marginTop: 24,
        marginBottom: 10,
        alignSelf: 'flex-start',
        flexDirection: 'row',
        alignItems: 'center',
    },
    recentContainer: {
        paddingHorizontal: 24,
        marginBottom: 20,
    },
    recentCard: {
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 16,
        marginRight: 16,
        width: 160,
        height: 180,
        justifyContent: 'space-between',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    iconBox: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: '#002259',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    cardTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 4,
    },
    cardSubtitle: {
        fontSize: 12,
        color: '#666',
    },
    pillButton: {
        backgroundColor: '#E6EBF5',
        borderRadius: 8,
        paddingVertical: 6,
        paddingHorizontal: 12,
        alignSelf: 'flex-start',
        marginTop: 8,
    },
    pillText: {
        color: '#004aad',
        fontSize: 12,
        fontWeight: '600',
    },
    listSection: {
        paddingHorizontal: 24,
        paddingBottom: 20,
    },
    sectionHeaderDark: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#002259',
        marginTop: 10,
        marginBottom: 16,
        flexDirection: 'row',
        alignItems: 'center',
    },
    listItemCard: {
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        flexDirection: 'row',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    listIconBox: {
        width: 56,
        height: 56,
        borderRadius: 12,
        backgroundColor: '#002259',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    listContent: {
        flex: 1,
        justifyContent: 'center',
    },
    tagsContainer: {
        flexDirection: 'row',
        marginTop: 8,
        flexWrap: 'wrap',
    },
    tag: {
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 6,
        marginRight: 8,
        marginBottom: 4,
    },
    tagText: {
        fontSize: 10,
        fontWeight: '600',
    },
    timeText: {
        fontSize: 12,
        color: '#777',
        marginTop: 8,
        marginLeft: 'auto',
    },
    logoutButton: {
        padding: 10,
        position: 'absolute',
        top: 40,
        right: 20,
        zIndex: 10,
    },
    bottomLogoutButton: {
        marginHorizontal: 24,
        marginBottom: 40,
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: '#002259',
        borderRadius: 8,
        height: 48,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
    },
    bottomLogoutText: {
        color: '#002259',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 8,
    },

    // --- Tab Bar ---
    tabBarContainer: {
        flexDirection: 'row',
        height: 70,
        backgroundColor: 'white',
        borderTopWidth: 1,
        borderTopColor: '#eee',
        paddingBottom: 10,
        justifyContent: 'space-around',
        alignItems: 'center',
    },
    tabButton: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 10,
    },
    tabText: {
        fontSize: 10,
        marginTop: 4,
        fontWeight: '500',
    },

    // --- Achievements Screen ---
    achievementsHeader: {
        backgroundColor: '#002259',
        paddingTop: 0,
        paddingBottom: 24,
        borderBottomLeftRadius: 24,
        borderBottomRightRadius: 24,
    },
    statsCard: {
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderRadius: 16,
        marginHorizontal: 24,
        padding: 16,
        marginTop: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    statsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 16,
    },
    statItem: {
        alignItems: 'center',
        flex: 1,
    },
    statValue: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
        marginTop: 4,
    },
    statLabel: {
        color: 'rgba(255,255,255,0.7)',
        fontSize: 10,
    },
    pointsBadge: {
        backgroundColor: '#FFC107',
        width: 48,
        height: 48,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    mainPointsText: {
        color: 'white',
        fontSize: 32,
        fontWeight: 'bold',
        marginLeft: 16,
    },
    toggleContainer: {
        flexDirection: 'row',
        backgroundColor: 'rgba(255,255,255,0.15)',
        marginHorizontal: 24,
        marginTop: 24,
        borderRadius: 12,
        padding: 4,
    },
    toggleButton: {
        flex: 1,
        height: 36,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 8,
    },
    toggleButtonActive: {
        backgroundColor: '#002259',
    },
    toggleText: {
        color: 'white',
        fontSize: 14,
        fontWeight: '600',
    },
    toggleTextActive: {
        color: 'white',
    },
    toggleTextInactive: {
        color: 'rgba(255,255,255,0.6)',
    },
    challengeCard: {
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 24,
        marginBottom: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
    },
    progressBarBackground: {
        height: 8,
        backgroundColor: '#F0F0F0',
        borderRadius: 4,
        marginTop: 12,
        marginBottom: 8,
        width: '100%',
    },
    progressBarFill: {
        height: 8,
        borderRadius: 4,
    },
    expiringTag: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    expiringText: {
        fontSize: 12,
        color: '#666',
        marginLeft: 4,
    },

    // --- Profile Screen ---
    profileHeader: {
        alignItems: 'center',
        marginTop: 40,
        marginBottom: 40,
    },
    avatarPlaceholder: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#002259',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    studentInfoCard: {
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 24,
        marginHorizontal: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        marginBottom: 24,
    },
    infoLabel: {
        fontSize: 12,
        color: '#666',
        marginBottom: 2,
    },
    infoValue: {
        fontSize: 16,
        color: '#333',
        fontWeight: '500',
        marginBottom: 16,
    },
    // --- Ranking Screen ---
    rankingHeader: {
        backgroundColor: '#002259',
        paddingTop: 10,
        paddingBottom: 30,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        alignItems: 'center',
    },
    rankingTitle: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
    },
    rankingSubtitle: {
        color: 'rgba(255,255,255,0.7)',
        fontSize: 12,
        marginBottom: 20,
    },
    podiumContainer: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        justifyContent: 'center',
        marginTop: 20,
        marginBottom: -30, // Overlap into the list area
        zIndex: 10,
    },
    podiumPlace: {
        alignItems: 'center',
        marginHorizontal: 8,
    },
    podiumAvatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#E0E0E0',
        marginBottom: 8,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: 'white',
    },
    starBadge: {
        position: 'absolute',
        top: -10,
        right: -10,
        backgroundColor: '#FFC107',
        borderRadius: 10,
        width: 20,
        height: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    podiumBase: {
        width: 80,
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 10,
    },
    rankNumber: {
        color: 'white',
        fontSize: 24,
        fontWeight: 'bold',
    },
    rankName: {
        color: '#002259',
        fontSize: 12,
        fontWeight: 'bold',
        marginTop: 4,
        textAlign: 'center',
    },
    rankScore: {
        color: '#666',
        fontSize: 10,
        marginBottom: 8,
        flexDirection: 'row',
        alignItems: 'center'
    },
    rankingList: {
        marginTop: 40,
        paddingHorizontal: 24,
        paddingBottom: 40,
    },
    rankingItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 12,
        marginBottom: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    rankPositionCircle: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#F5F5F5',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    rankPositionText: {
        color: '#666',
        fontWeight: 'bold',
    },

    // --- Edit Score Screen ---
    editScoreContainer: {
        flex: 1,
        backgroundColor: '#F5F5F5',
    },
    editHeader: {
        backgroundColor: '#002259',
        paddingTop: 50,
        paddingBottom: 24,
        paddingHorizontal: 24,
        flexDirection: 'row',
        alignItems: 'center',
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    editHeaderTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: 'white',
    },
    editHeaderSubtitle: {
        fontSize: 12,
        color: 'rgba(255,255,255,0.7)',
    },
    editFormCard: {
        backgroundColor: 'white',
        margin: 24,
        borderRadius: 24,
        padding: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    formLabel: {
        fontSize: 14,
        color: '#666',
        marginBottom: 8,
        marginTop: 16,
    },
    requiredMark: {
        color: '#D32F2F',
    },
    formInput: {
        borderWidth: 1,
        borderColor: '#E0E0E0',
        borderRadius: 8,
        padding: 12,
        fontSize: 16,
        color: '#333',
        backgroundColor: 'white',
    },
    difficultyContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 8,
    },
    difficultyButton: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 8,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        marginHorizontal: 4,
    },
    difficultyButtonActive: {
        backgroundColor: '#002259',
    },
    difficultyText: {
        fontSize: 12,
        color: '#666',
        fontWeight: '500',
    },
    difficultyTextActive: {
        color: 'white',
    },
    uploadContainer: {
        borderWidth: 1,
        borderColor: '#E0E0E0',
        borderRadius: 12,
        backgroundColor: '#FAFAFA',
        height: 120,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 8,
        marginBottom: 24,
    },
    uploadText: {
        color: '#666',
        fontSize: 14,
        marginTop: 8,
        fontWeight: '500',
    },
    uploadSubtext: {
        color: '#999',
        fontSize: 10,
        marginTop: 4,
    },
    formActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 24,
    },
    cancelButton: {
        flex: 1,
        backgroundColor: '#F5F5F5',
        paddingVertical: 14,
        borderRadius: 8,
        alignItems: 'center',
        marginRight: 16,
    },
    cancelButtonText: {
        color: '#666',
        fontSize: 16,
        fontWeight: '600',
    },
    updateButton: {
        flex: 1.5,
        backgroundColor: '#002259',
        paddingVertical: 14,
        borderRadius: 8,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
    },
    updateButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 8,
    },

    // --- Admin Actions ---
    actionButtonsContainer: {
        position: 'absolute',
        right: 16,
        top: 16,
        flexDirection: 'column',
    },
    actionButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    editButton: {
        backgroundColor: '#E3F2FD',
    },
    deleteButton: {
        backgroundColor: '#FFEBEE',
    },
});
